apiVersion: v1
kind: Service
metadata:
  name: demo-userportal-service
spec:
  selector:
    app: demo-userportal
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: nginx-port
      protocol: TCP
      type: NodePort
