apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-userportal-deployment
  labels:
    app: demo-userportal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-userportal
  template:
    metadata:
      labels:
        app: demo-userportal
    spec:
      containers:
        - name: demo-userportal
          image: vdigital/demo-userportal:e4132379
          ports:
            - name: nginx-port
              containerPort: 80
