apiVersion: v1
kind: Service
metadata:
  name: demo-userportal-service
spec:
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: nginx-port
      protocol: TCP
    selector:
      app: demo-userportal
    type: NodePort
